name: Update Changelog

on:
  push:
    branches: [ main ]
    paths:
      - 'gpt5/**'
      - '.github/workflows/changelog.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Generate CHANGELOG
        run: |
          python -m gpt5 report changelog --output CHANGELOG.md --json
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md || true
          if git diff --cached --quiet; then
            echo "No changelog changes"
          else
            git commit -m "docs(changelog): update CHANGELOG.md"
            git push
          fi

