name: Smoke Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Sanity CLI
        run: |
          python -m gpt5 --help | head -n 5
          python -m gpt5 plan "CI sanity" --json | head -n 1
          python -m gpt5 math expr "sin(1)**2+cos(1)**2" --json
          python -m gpt5 math fft --data "[0,1,0,-1]" --rate 4 --json
